apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: atlas-app
  name: atlas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-app
  template:
    metadata:
      labels:
        app: atlas-app
    spec:
      containers:
      - image: atlas-app:latest
        imagePullPolicy: Never
        name: atlas-container
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
