apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-deployment
  labels:
    app: atlas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-app
  template:
    metadata:
      labels:
        app: atlas-app
    spec:
      containers:
      - name: atlas-container
        image: atlas-app:latest
        ports:
        - containerPort: 8000
        readinessProbe:                   # optional but recommended
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
