# k8s/atlas-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-deployment
  labels:
    app: atlas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-app
  template:
    metadata:
      labels:
        app: atlas-app
    spec:
      containers:
        - name: atlas-app
          image: atlas-app:latest
          ports:
            - containerPort: 5000
# k8s/atlas-service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: atlas-svc
spec:
  type: NodePort
  selector:
    app: atlas-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080

